@baseScheduler=http://localhost:8080
@baseWorkflowManager=http://localhost:8081

###
POST {{baseWorkflowManager}}/workflows
Content-Type: application/yaml

name: "IFTEST"
args:
  - property1:
      default: "value"
  - property2:
      default: "value"
steps:
  - echo1:
      service: "echo_service" # (default)
      task: "echo"
      input:
        msg: "$args.property1"
  - check-property:
      service: 'native'
      task: "if"
      input:
        leftValue: "echo1.msg"
        rightValue: "$args.property2"
        operator: "=="
        onTrue: "echo2"
        onFalse: "continue"
  - premature:
      service: "native"
      task: "abort"
  - echo2:
      service: "echo_service"
      task: "echo"
      input:
        msg: "check-property.result"



###
GET {{baseWorkflowManager}}/workflows

###
DELETE {{baseWorkflowManager}}/workflows/5

###
POST {{baseWorkflowManager}}/triggers
Content-Type: application/json

{
  "workflowName": "IFTEST",
  "tags": ["hola","chau"],
  "parameters": {
    "cronDefinition": "* * * * * *",
    "delayed": "30"
  },
  "args": {
    "property1": "asd",
    "property2": "chau"
  }
}

###
POST {{baseWorkflowManager}}/triggers
Content-Type: application/json

{
  "workflowName": "IFTEST",
  "tags": [],
  "parameters": {},
  "args": {
    "property1": "hola",
    "property2": "chau"
  }
}


###

GET http://localhost:8080/healthcheck

###
GET {{baseScheduler}}/executions/d662bcf5-327d-446e-8780-5bbf72c77e1d

###
POST {{baseScheduler}}/cancel-execution/da0f328e-3915-49b2-a416-0865427a649c

###
POST {{baseScheduler}}/cancel-execution/
Content-Type: application/json

{
  "tags": ["hola","chau"]
}
