###
POST http://localhost:8080/workflows
Content-Type: application/yaml

name: "C workflow"
args:
  - property1:
      default: "value"
  - property2:
      default: "value"
steps:
  - echo1:
      service: "echo-service" # (default)
      task: "echo"
      input:
        msg: "$args.property1"


###
GET http://localhost:8080/workflows

###
POST http://localhost:8080/executions
Content-Type: application/json

{
  "workflowName": "C workflow",
  "tags": [],
  "parameters": {},
  "args": {
    "property1": "hola",
    "property2": "chau"
  }
}

###

GET http://localhost:8080/healthcheck

