apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-auth
data:
  workflows_db_pass: {{ .Values.workflows_db_pass | b64enc }}
  workflows_db_user: {{ .Values.workflows_db_user | b64enc}}
  workflows_db_db: {{ .Values.workflows_db_db | b64enc}}