{{- range .Values.available_namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: {{ . }}
type: Opaque
data:
  .dockerconfigjson: {{ $.Values.dockerconfigjsonb64 | quote }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}