services:
  scheduler:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - broker
    networks:
      - db-network
      - bus-network
      - etcd-network
    env_file:
      - .env.docker
    environment:
      - ENV_MODE=production
  db:
    image: "postgres"
    env_file:
      - .env.docker
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - db-network
      - default
  broker:
    image: apache/kafka:latest
    container_name: broker
    env_file:
      - .env.local.kafka
    ports:
      - "9092:9092"
    volumes:
      - broker-data:/var/lib/kafka/data
    networks:
      - default
      - bus-network
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
  etcd:
    image: bitnami/etcd:latest
    env_file:
      - .env.etcd
    volumes:
        - etcd-data:/bitnami/etcd
    networks:
        - etcd-network
        - default
    ports:
      - "2379:2379"
      - "2380:2380"

networks:
  db-network:
    driver: bridge
  bus-network:
    driver: bridge
  etcd-network:
    driver: bridge

volumes:
  db-data:
  etcd-data:
  broker-data:
