apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-auth
data:
  scheduler_db_pass: {{ .Values.scheduler_db_pass | b64enc }}
  scheduler_db_user: {{ .Values.scheduler_db_user | b64enc}}
  scheduler_db_db: {{ .Values.scheduler_db_db | b64enc}}