FROM golang:1.23 AS builder

WORKDIR /usr/src/app
RUN apt-get update && apt-get install bc

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

ENTRYPOINT [ "go", "test", "./..." ]