services:
  web:
    build: .
    ports:
      - "8081:8080"
      - "50051:9090"
    depends_on:
      - db
    networks:
      - db-network
      - default
      - scheduler_bus-network
    env_file:
      - .env.local
  db:
    image: "postgres"
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - db-network

networks:
  db-network:
    internal: true
  scheduler_bus-network:
    external: true

volumes:
  db-data: